-- Run this in your Supabase SQL Editor

create table habits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  target_frequency int default 1, -- e.g., times per week/day
  completed_dates text[] default '{}'::text[] -- Array of dates when the habit was completed (ISO strings)
);
